/** Rótulos em linguagem simples para o registro de atividades (auditoria). */
export const ROTULO_ACAO: Record<string, string> = {
  inserir: "Criou",
  alterar: "Alterou",
  excluir: "Excluiu",
  login: "Entrou no portal",
  logout: "Saiu do portal",
  encerrar_sessao: "Encerrou uma sessão",
  encerrar_sessoes: "Encerrou as sessões de um usuário",
  senha_alterada: "Trocou a senha",
  senha_redefinida: "Redefiniu a senha",
  mfa_removido: "Desativou a verificação em duas etapas",
  mfa_redefinido: "Redefiniu a verificação em duas etapas de um usuário",
  convite: "Convidou um usuário",
  convite_reenviado: "Gerou novo link de acesso",
  desativar_usuario: "Desativou um usuário",
  anonimizar_usuario: "Anonimizou um usuário (LGPD)",
  exportar_dados_pessoais: "Baixou os próprios dados (LGPD)",
  expurgar_documentos: "Eliminou documentos com prazo de guarda vencido",
  exportacao: "Exportou um relatório",
  download_lote: "Baixou documentos em lote",
  gerar_tarefas: "Gerou tarefas de obrigações",
  sincronizar_tarefas: "Atualizou as tarefas de uma empresa",
  recalcular_tarefas: "Recalculou prazos de tarefas",
  aplicar_norma: "Aplicou uma atualização normativa",
  notificacoes_aparelho_ativadas: "Ativou os avisos num aparelho",
  notificacoes_aparelho_desativadas: "Desativou os avisos num aparelho",
};

export const ROTULO_ENTIDADE: Record<string, string> = {
  baixas: "pagamento/recebimento",
  categorias_financeiras: "categoria financeira",
  checklist_itens: "item do checklist",
  checklist_modelos: "modelo de checklist",
  competencias: "competência (fechamento)",
  atualizacoes_normativas: "atualização normativa",
  conciliacoes: "conciliação",
  contas_financeiras: "conta financeira",
  convites: "convite",
  documentos: "documento",
  empresa_contatos: "contato da empresa",
  empresa_membros: "acesso de usuário à empresa",
  empresa_obrigacoes: "calendário de obrigações da empresa",
  empresa_regimes: "regime tributário da empresa",
  empresas: "empresa",
  escritorio: "configurações do escritório",
  estoques: "estoque",
  feriados: "feriado",
  importacoes: "importação",
  lancamentos: "lançamento financeiro",
  obrigacao_regras: "regra de obrigação",
  obrigacoes: "obrigação do catálogo",
  perfis: "usuário",
  push_aparelhos: "aparelho com avisos",
  relatorios: "relatório",
  relatorios_publicados: "relatório publicado",
  sessoes: "sessão",
  tarefas: "tarefa de obrigação",
  transferencias: "transferência",
};

export const ACOES_SEGURANCA = [
  "login",
  "logout",
  "encerrar_sessao",
  "encerrar_sessoes",
  "senha_alterada",
  "senha_redefinida",
  "mfa_removido",
  "mfa_redefinido",
  "convite",
  "convite_reenviado",
  "desativar_usuario",
  "anonimizar_usuario",
  "exportar_dados_pessoais",
  "notificacoes_aparelho_ativadas",
  "notificacoes_aparelho_desativadas",
];

export function descreverEvento(acao: string, entidade: string) {
  if (acao === "inserir" || acao === "alterar" || acao === "excluir") return `${ROTULO_ACAO[acao]} ${ROTULO_ENTIDADE[entidade] ?? entidade}`;
  return ROTULO_ACAO[acao] ?? `${acao.replace(/_/g, " ")} (${ROTULO_ENTIDADE[entidade] ?? entidade})`;
}
